### ISSUE TITLE
ColorMeNotifs taking color from “Up Next” instead of current track

### ISSUE THREAD

**Issue by iancbogue** [Nosskirneh/NextUp-Public#33]
![D5072704-1807-481F-A940-78F30A7254DB](https://user-images.githubusercontent.com/18062067/77146095-79636200-6a47-11ea-8f6f-97ed38e5a94d.png)
![D784D700-CDB2-4C05-9BAA-7327882BCAE0](https://user-images.githubusercontent.com/18062067/77145954-1a055200-6a47-11ea-9456-f19d8538b8dd.png)
![8C9F8070-EEB3-494B-9572-DCCACC0174E1](https://user-images.githubusercontent.com/18062067/77146367-22aa5800-6a48-11ea-9bbe-f86f7db8208e.gif)

If I use the X button provided by the tweak, ColorMeNotifs will take the color from the next track that shows, regardless of if the album art is shown or hidden. Pressing any other button (pause, forward, back) resets the color to the playing track.

LMK if I should report this to the ColorMeNotifs’ dev as well.

**Comment by Nosskirneh** [comment]
It would seem as if ColorMeNotifs hooks the setter of the artwork in the `MediaControlsHeaderView` class to get the event of new track and at the same time calculate a function on the color.

To me, this is badly done. The hook would work for any instance of that class, which is why this doesn’t work with NextUp.

The correct way would be to subscribe to notifications that provide information about the artwork and then get the reference to the media widget to colorize it. I will be closing this issue as there’s nothing I can do in NextUp to fix this. You are more than welcome to link my comment to the developer of the other tweak. I can assist him/her with hints if there’s any questions on how to implement this in a more robust way.
